name: 'Hooop Cloud'
description: 'Hooop Cloud'
author: 'Aditya Borkar'

branding:
  color: purple
  icon: 'box'

runs:
  using: node20
  main: dist/index.js

inputs:
  package-manager:
    description: 'The package manager to use'
    required: true
